// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAQNUU76X-AA6RdEVk445WgJGJxXa21Q',
    appId: '1:307649012870:web:9c4a6453b8753c40be5d07',
    messagingSenderId: '307649012870',
    projectId: 'she-fit-97ccf',
    authDomain: 'she-fit-97ccf.firebaseapp.com',
    storageBucket: 'she-fit-97ccf.appspot.com',
    measurementId: 'G-7HBYBK0B3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHsGCxD9fp7FE64auo9ZPfJCwhNqWSZx4',
    appId: '1:307649012870:android:a815775b0bbb5551be5d07',
    messagingSenderId: '307649012870',
    projectId: 'she-fit-97ccf',
    storageBucket: 'she-fit-97ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX7O7MDkPgeNwapjvKefvBWw5caufCyu8',
    appId: '1:307649012870:ios:77ab2c9fa474016abe5d07',
    messagingSenderId: '307649012870',
    projectId: 'she-fit-97ccf',
    storageBucket: 'she-fit-97ccf.appspot.com',
    iosBundleId: 'com.example.sheFitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX7O7MDkPgeNwapjvKefvBWw5caufCyu8',
    appId: '1:307649012870:ios:77ab2c9fa474016abe5d07',
    messagingSenderId: '307649012870',
    projectId: 'she-fit-97ccf',
    storageBucket: 'she-fit-97ccf.appspot.com',
    iosBundleId: 'com.example.sheFitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAQNUU76X-AA6RdEVk445WgJGJxXa21Q',
    appId: '1:307649012870:web:4f3580317cabf18ebe5d07',
    messagingSenderId: '307649012870',
    projectId: 'she-fit-97ccf',
    authDomain: 'she-fit-97ccf.firebaseapp.com',
    storageBucket: 'she-fit-97ccf.appspot.com',
    measurementId: 'G-YY5G2GWXMS',
  );
}
